freedombox/freedom-maker

Makefile

The changes in this branch introduce the ability to build VirtualBox images for both i386 and amd64 architectures. The target `virtualbox` still builds the i386 architecture image.  To build amd64 image the target is `virtualbox-amd64`.
Both images have been tested by building and booting them in VirtualBox.

Ability to build VirtualBox images with i386 and amd64 architectures

---

Makefile
bin/freedombox-customize
bin/mk_freedombox_image

Currently if a local Debian mirror such as apt-cacher-ng is set
during build, the resulting images will also contain the same
mirror which is not desirable.
This patch separates the mirror used to build the image from the
mirror used inside the final image.  By default build mirror and
image mirror are the same.  However, build mirror can be specified
by passing an environment variable BUILD_MIRROR to the make command.
make -e BUILD_MIRROR=<build_mirror>
user concern to set mirrors.

Add ability to set build and image mirrors separately

---

.gitignore
README

I'm not too familiar with freedom-maker, so please correct my mistakes, I just found the documentation to be a bit out of date.
Is http://anonscm.debian.org/git/freedombox/freedom-maker.git still the preferred source for freedom-maker, or should we point users to github?

Updated installation instructions

---

bin/fetch-new-vmdebootstrap
vendor-patches/vmdebootstrap/03-roottype-btrfs-bts-741223.patch

Switch to vmdebootstrap-0.8 and refresh the btrfs patch. Debian bug #786767 (i386 arch kernel package not found) is fixed in vmdebootstrap 0.8.
I checked that I could build images for each target, except for raspberry (still hangs during kernel update). I also checked that the virtualbox image could boot, but couldn't test much more due to the network interface renaming issue.

Use vmdebootstrap-0.8

---

bin/mk_freedombox_image

With the option set, vmdebootstrap will generate an /etc/network/interfaces with DHCP configuration for eth0.  Earlier this file was getting overwritten so no harm done.  But now, we have a patch proposed to freedombox-setup that uses network-manager and will suffer if eth0 is mentioned in /etc/network/interfaces.

Remove unneeded DHCP config option to vmdebootstrap

---

Makefile
bin/freedombox-customize
bin/hardware-setup
bin/mk_freedombox_image

The pull request adds support for:
- A20 OLinuXino Lime2
- A20 OLinuXino MICRO
I have tested with A20 OLinuXino MICRO to boot well and access Plinth functions. I have also built Cubietruck image to check for regressions and test it.  I could not test Lime2 due to poor power supply.
The change to explicitly set the value of ${fdtfile} in u-boot script is something I am sure is the best one.  When we choose the appropriate u-boot for the device, it comes hardcoded with the appropriate DTB value for this variable.  If we can remove the detection of kernel version using a DTB file name (say by assuming there will be only one kernel installed at the time of script execution and that it will contain the necessary DTB), then we can generalize a20_setup() to work for all Allwinner A20 devices. …

Support A20 OLinuXino Lime2 and MICRO

---

Makefile
README

Virtualbox is not available on Trisquel, so qemu is an alternative. This generates qcow2 images which can then be run using qemu-system-i386 or qemu-system-x86_64. It requires the qemu package to be installed.

Create qemu images

---

bin/mk_freedombox_image

The following patch is untested even though it comes with high confidence.  When we make the release builds for 0.7 soon, we will be testing this on all supported A20 devices.
The initrd creation tools can't handle the /boot partition being vfat
type.  Permissions and ownership can't be preserved and typical kernel
upgrade fails.
On A20 devices, the BROM (32kb of non-writable GPL2 code) boots disks in
a particular order.  A Secondar Program Loader (SPL) is booted at 8K
offset on the disk which then boots u-boot at another offset.  BROM does
not need to understand the filesystem to boot a disk.  Neither does the
SPL.  After this U-boot loads kernel, initrd and device tree before
starting the kernel.  For us, SPL and U-boot both come from mainline
U-boot which supports booting ext2.

Use ext2 for boot partition on A20 devices

---

bin/freedombox-customize
bin/passwd-in-image

The 'fbx' user will have password disabled by default.  This is only a
problem for users who want to login on console before Plinth can create
an administrative user during first boot.  This only happens when Plinth
is not accessible due to various reasons.  While we continue to fix
problems that will make Plinth a reliable option, our fallback option is
to use a password setting tool on the downloaded image.
The password setting tool will loop mount the image and set a password
inside the image for the 'fbx' user.  This is, for now, a command line
tool that requires some knowledge of UNIX command line.  However, if the
users are wishing to login to shell as 'fbx' user, so is that process.
Essentially, in the normal flow, users won't need 'fbx' user and will
use the first boot user create …

Don't set password for user 'fbx'

---

freedommaker/freedombox-customize

Currently, running hardware script when there are spaces in paths fails. The patch fixes it.

Handle spaces in paths properly

---

freedommaker/freedombox-customize

This allows plinth --setup to run properly.
This patch was actually tested on top of my cubietruck-fixes.  But it is really independent.  So, I am submitting it separately.  To test, I have built and amd64 image with corresponding patch to run plinth --setup in freedombox-setup.  The setup log showed that mounts happed properly and so did unmounts. Making use of the mounts, Plinth setup also ran as expected.

Mount basic file systems during customize

---

freedommaker/freedombox-customize
freedommaker/hardware-setup

The patchset fixes the following issues:
- When output directory is absolute path, writing u-boot firmware to image fails.
- Use flash-kernel for A20 based devices since it seems to work fine.
- Remove subvol=@ root file system parameter so that we work properly with upstream vmdebootstrap.
I have tested all the above by building a Cubietruck image with this branch.

Cubietruck and other fixes

---

README
freedommaker/builder.py

pxz spawns multiple threads to compress.  By default the number of
threads are the same as number of CPU cores.  The compression factor
usually suffers but only by a few megabytes.
With this change x86 build takes just 10 minutes on SSD + 8 cores.

Use pxz for compression with full CPU usage

---

freedommaker/hardware-setup

The first patch removes adding console settings to /etc/inittab as this is unnecessary with systemd.
Second patch uses flash-kernel for beaglebone. Adding `console=ttyO0` is necessary in this case as the boot loader does not automatically this to the kernel arguments.
I have tested the following:
* I have tested a Cubietruck image built with this patch.
* I have tested a Beaglebone image built with this patch.
* The root file system was being found using UUID= argument picked up from /etc/fstab and added as /conf/conf.d/default_root into initramfs.  This solved the problem with BBB unpredictable root devices.
* For both images, the console was available on serial debug terminal.
* Patch was slightly different when i built images.  I was doing additional ttyS0 argument to …

Beagle Bone Black cleanup

---

freedommaker/freedombox-customize

Last night I had several build failures without this patch.  There is some weird issues with bind mounts when doing several builds at the same time on same machine.
Ideally, I would like avoid this patch.  However, it is not bad; if we fail to unmount any of the steps, it will lead to failure in final umount anyway.

Ignore errors during unmount

---

freedommaker/builder.py
freedommaker/hardware-setup
freedommaker/tests/test_invocation.py

Closes: #67.  Use of USB Wi-Fi dongles with free firmware are
recommended instead.
Freedom maker test cases are running fine.  Full image build is ongoing, will update when it is completed.

Remove non-free Wi-Fi firmware from Dreamplug imgs

---

bin/passwd-in-image

After attaching a VM image to a /dev/nbd? device, partition devices such
as /dev/nbd7p1 are no longer created.  Run partprobe on the device to
create these partition device.
Closes #62.

passwd-in-image: Probe partitions for VM images

---

freedommaker/builder.py
freedommaker/tests/test_invocation.py

Remove minbase as debootstrap variant:
For all images, uniformly use 'no variant'.  According to debootstrap
manual page, providing no variant will result in installing packages
with 'Priority: important' where as when using 'minbase' as variant only
'apt' is installed.  All packages marked as 'Priority: required' are
included in both cases.  See debootstrap:scripts/sid:work_out_debs().
This means:
- All images will have packages installed uniformly.  We can document
the features reliably and depend on the packages reliably.
- There is no need to explictly list and manage important packages.
Packages marked important by Debian developers will automatically be
installed.
Remove explicit inclusion of important packages:
As we specify no variant to debootstrap, all important packages are …

Remove debootstrap variants

---

freedommaker/builder.py
freedommaker/freedombox-customize
freedommaker/hardware-setup

I haven't been able to get this to actually boot yet, so further changes may be required.
- Create /boot/firmware partition as vfat
- Use ext2 for /boot
- Use u-boot-rpi and armmp kernel
- Use flash-kernel to copy kernel to /boot
Notes:
- There is a different u-boot binary for Raspberry Pi 3, so we will likely need a separate image for it.
- I thought flash-kernel should be triggered automatically at install, but that wasn't happening. Will need to investigate further.
The partition table looks like this:
```
Number  Start   End     Size    Type     File system  Flags
1      1049kB  134MB   133MB   primary  fat16
2      160MB   282MB   122MB   primary  ext2         boot
3      282MB   3799MB  3517MB  primary  btrfs
```
Here are the files under /boot:
/boot/lost+found …

WIP: Use Debian kernel and u-boot for Raspberry Pi 2

---

freedommaker/builder.py
freedommaker/freedombox-customize
freedommaker/hardware-setup

Add support for pcDuino3/pcDuino3s.  Thanks to hardware donation by FreedomBox Foundation, I have tested the following functions:
- HDMI output
- USB ports (two work, one does not)
- Network
- No problem in setup log
- No problem in firstboot.log
- Basic plinth first boot wizard
- Boot process shows no problem
Most of the changes are simply untabify.

Add support for pcDuino3/pcDuino3S

---

freedommaker/freedombox-customize

Create a file called /var/lib/freedombox/is-freedombox-disk-image to
indicate that this image was created by freedom-maker.

WIP: File-based flag to indicate FreedomBox images

---

freedommaker/freedombox-customize

This is so /etc/resolv.conf link target will exist. It resolves name resolution issues during the customize script. Fixes #86.

Mount /run during customize script
